### ISSUE TITLE
Receiver class dev.openfeature.contrib.providers.flagd.FlagdProvider does not define or inherit an implementation of getState()

### ISSUE THREAD

**Issue by DarekDan** [open-feature/java-sdk-contrib#1004]
```
java.lang.AbstractMethodError: Receiver class dev.openfeature.contrib.providers.flagd.FlagdProvider does not define or inherit an implementation of the resolved method 'dev.openfeature.sdk.ProviderState getState()' of interface dev.openfeature.sdk.FeatureProvider. Selected method is 'abstract dev.openfeature.sdk.ProviderState dev.openfeature.sdk.EventProvider.getState()'.

	at dev.openfeature.sdk.ProviderRepository.initializeProvider(ProviderRepository.java:135)
	at dev.openfeature.sdk.ProviderRepository.prepareAndInitializeProvider(ProviderRepository.java:120)
	at dev.openfeature.sdk.ProviderRepository.setProvider(ProviderRepository.java:98)
	at dev.openfeature.sdk.OpenFeatureAPI.setProviderAndWait(OpenFeatureAPI.java:234)
```

Is this known and being worked on, yet? Happy to take a stab at it. It is causing problems when `setProviderAndWait()` is called.

**Comment by aepfli** [comment]
depending on which version of the sdk and the flagd provider you are using. we recently changed the implementation detail within the base sdk, and there is no usage of `getState` anymore. aka the state handling is moved from the provider into the sdk - https://github.com/open-feature/java-sdk/issues/844 

which version of the java sdk are you using? is it 1.12 or bigger? see https://github.com/open-feature/java-sdk-contrib/pull/964/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R69 were we added this change

**Comment by DarekDan** [comment]
I was using 1.10.0. After upgrade to 1.12.0, with no other code changes I am getting "FlagEvaluationDetails(flagKey=null, value=, variant=null, reason=ERROR, errorCode=PROVIDER_NOT_READY, errorMessage=provider not yet initialized, flagMetadata=dev.openfeature.sdk.ImmutableMetadata@3b)".

`initialize()` on a provider was not required before, but after adding it with a new `MutableContext`, my tests are passing again. Thank you for the tip. One can also simply use `setProviderAndWait()` again.
