### ISSUE TITLE
[Junit5 extension] Add Interception of @ParameterizedTest to JUnit Open Feature Extension

### ISSUE THREAD

**Issue by sebastian-zahrhuber** [open-feature/java-sdk-contrib#1091]
If the JUnit Open Feature Extension is used, a developer needs to use the `@Flag` annotation on `@Test `and `@ParameterizedTest` methods.

By intercepting the test method, the `OpenFeatureExtension` sets the current namespace for the `TestProvider` which is used later on in the evaluation. This is done by implementing the interface `InvocationInterceptor` and overriding the method `interceptTestMethod`.
Actually, the method `interceptTestMethod` does not intercept methods annotated with `@ParameterizedTest`. This leads to the issue that during the feature flag evaluation, the current namespace is not set int the `TestProvider` and therefore, the flag values cannot be stubbed with the annotation `@Flag`.
To fix the issue not only the method `interceptTestMethod` must be overridden, but `InvocationInterceptor.interceptTestTemplateMethod()` must be overridden as well.

 

### A/C

@Flag annotation mocks feature flags on test methods annotated with @Test and @ParameterizedTest

**Comment by beeme1mr** [comment]
Hey @sebastian-zahrhuber, is this something you'd be willing to work on? FYI @aepfli.

**Comment by aepfli** [comment]
it seems like this issue also relates somehow to https://github.com/open-feature/java-sdk-contrib/issues/957

**Comment by sebastian-zahrhuber** [comment]
Hi @beeme1mr , to be honest, we don't have many resources left in the team, but if it speeds up the process, I can take this issue since we currently depend on the change
