### ISSUE TITLE
[flagd-provider] add caching

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#139]
Implement caching based on the strategy defined [here](https://github.com/open-feature/flagd/blob/main/docs/caching.md).

Go implementation, for reference: https://github.com/open-feature/go-sdk-contrib/pull/48

**Comment by skyerus** [comment]
Base implementation is done, change is needed to integrate consolidated configuration event:
https://github.com/open-feature/flagd/pull/241
