### ISSUE TITLE
Flagsmith classes not public

### ISSUE THREAD

**Issue by glaucioscheibel** [open-feature/java-sdk-contrib#211]
Flagsmith provider class and option class was created using package restricted access, so examples doesn't work.

**Comment by toddbaert** [comment]
@glaucioscheibel Thanks for the report!

I've opened a [fix PR](https://github.com/open-feature/java-sdk-contrib/pull/213)

**Comment by toddbaert** [comment]
Fixed with https://github.com/open-feature/java-sdk-contrib/pull/213

**Comment by toddbaert** [comment]
This fix will be released when https://github.com/open-feature/java-sdk-contrib/pull/209 is merged (plus an hour or so wait for Maven to index it).
