### ISSUE TITLE
[flagd-provider] Reduce duplication across resolver functions

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#229]
We can probably use generics/lambdas to reduce some duplication across the resolvers.

**Comment by Kavindu-Dodan** [comment]
@toddbaert this seems be fixed with the new `resolve` function introduction [1]

[1] - https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java#L515

**Comment by toddbaert** [comment]
Yes, looks like I did this myself [here](https://github.com/open-feature/java-sdk-contrib/pull/234) and forgot to close this issue.

Closing.
