### ISSUE TITLE
Add automatic module names to all packages

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#261]
See [here](https://github.com/open-feature/java-sdk/pull/363), and the linked issue for details and background. [This blog post](http://branchandbound.net/blog/java/2017/12/automatic-module-name/) is also helpful, specifically for library maintainers.

In each module in this project, we should add this maven step (we could also add it in the parent POM and somehow grab the name dynamically). We should be careful that the module name matches the "highest level" package in the module.

**Comment by Kavindu-Dodan** [comment]
We should be able to utilize existing POM properties to derive unique names and make it a recommendation to add this to POM. And naming could be recommended to derive from existing values. For example,

```
<properties>
    <module-name>${parent.groupId}.${name}</module-name>
</properties>
```

flagd provider will result in - `dev.openfeature.contrib.flagd`

[1] - https://github.com/open-feature/java-sdk/pull/363#discussion_r1150853643
