### ISSUE TITLE
Remove deprecated methods of flagd

### ISSUE THREAD

**Issue by thisthat** [open-feature/java-sdk-contrib#295]
## Goal

Remove the methods annotated with `@Deprecated` in providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java

## Technical Details

With #294, several methods are deprecated because we moved to a builder pattern. We should remove them and the respective test code.

## Dependencies

- #294 
- #268

**Comment by toddbaert** [comment]
Personally I'm OK with removing these with a few weeks deprecation notice.

**Comment by Kavindu-Dodan** [comment]
Given that we already had the latest release out for several weeks [1], we can remove the deprecated constructors in favor of Build options.

Marking as `good first issue` as this is fairly straightforward :) 

[1] - https://github.com/open-feature/java-sdk-contrib/releases/tag/dev.openfeature.contrib.providers.flagd-v0.5.9
