### ISSUE TITLE
[flagd-provider] add events support 

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#314]
Once the java-sdk has `events` and `init/shutdown` support, we need to update the flagd-provider to emit events and do proper init/shutdown. We already have a stream implemented for cache-busing, so this should be pretty simple.

Definition of done:
- flagd does does startup logic (like initializing its stream) in `initialize` function
- flagd shuts down stream in `close/shutdown` function
- flagd emits appropriate events on flag changes, and errors
- associated testing

Blocked by:
- java-sdk implementation: https://github.com/open-feature/java-sdk/issues/437

Resources:
- [flag provider guide](https://github.com/open-feature/flagd/blob/main/docs/other_resources/creating_providers.md#provider-lifecycle-initialization-and-shutdown)

**Comment by thisthat** [comment]
Hey @toddbaert, I'd like to work on this issue
