### ISSUE TITLE
[FlagD] Refactor package structure and offload some responsibilities from FlagdProvider

### ISSUE THREAD

**Issue by thisthat** [open-feature/java-sdk-contrib#365]
### Problems

- Everything is bundled together into a single namespace which makes it hard to understand the responsibilities of each class. 
- The [current main commit](https://github.com/open-feature/java-sdk-contrib/blob/7b12a97dcf59bef42e8a53cc9d3b4523d106123f/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java#L208) allows for external entities to change the internal state of the communication of Flagd Provider. IMHO we should remove this from the API surface. 
- Unit and Integration tests are hard to write
- Review opportunities to add `log.debug` statements

### Suggestion

Refactor into modules as proposed: 
![image](https://github.com/open-feature/java-sdk-contrib/assets/992621/5e54ab69-9a3f-42a0-a8c8-4adfb0d1ec29)

**Comment by toddbaert** [comment]
I like this proposal. I think most other implementations have better separations of concerns like this.

One thing that could also be done beyond what you describe here, is to abstract the retry logic. The retry implementation is tightly coupled to gRPC of course, but the retry logic itself is not, and is prescribed to be the same for all languages for consistency.

**Comment by thisthat** [comment]
wouldn't make sense then to push the retry logic into to the SDK? 🤔 the provider has to return a functional interface implementation that performs the connection.

**Comment by toddbaert** [comment]
> wouldn't make sense then to push the retry logic into to the SDK? thinking the provider has to return a functional interface implementation that performs the connection.

The retry logic isn't specified in the OpenFeature SDK or spec, its just specified for our flagd implementations to be consistent. A reconnect logic spec for providers will probably never happen, some don't even need remote connections (read from files or env vars or whatever).
