### ISSUE TITLE
[flagd-provider] add guard before loading Epoll classes

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#402]
As per the recommendation from netty, we should [add a guard](https://github.com/netty/netty/issues/13523#issuecomment-1680917605) before loading the Epoll classes. It seems like they will revert the change that caused our issue, but using this guard will also help us to give helpful error messages if this native lib is missing.

cc @Kavindu-Dodan

**Comment by Kavindu-Dodan** [comment]
I will check and create a follow up PR
