### ISSUE TITLE
[go-feature-flag-provider] negative scenario: fix evaluating with different contexts

### ISSUE THREAD

**Issue by liran2000** [open-feature/java-sdk-contrib#405]
When evaluating a flag via the client, provider should handle cases like:

- without evaluation context.
- empty evaluation context, without targeting key.

if not supported, handle accordingly with a proper error code and documentation.

**Comment by toddbaert** [comment]
I'm not an expert on this provider... but for reference:

Some providers need a `targetingKey` (they have some requirement for a user identifier) and some do not. For those that do, if they receive a context without a `targetingKey`, they should throw a [TargetingKeyMissingError](https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/exceptions/TargetingKeyMissingError.java). If the context provided is invalid in any other way (as defined by that provider) they should throw a [InvalidContextError](https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/exceptions/InvalidContextError.java).

Does that solve this problem in your mind?

**Comment by liran2000** [comment]
Ok, thanks for the references, good to know. Then this issue is not severe but still exists, by its description:
"if not supported, handle accordingly with a proper error code, message and documentation."

Currently this provider throws [InvalidTargetingKey](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/go-feature-flag/src/main/java/dev/openfeature/contrib/providers/gofeatureflag/bean/GoFeatureFlagUser.java#L32), it can be replaced to [TargetingKeyMissingError](https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/exceptions/TargetingKeyMissingError.java).

Another something that may help, is documenting on this provider that it requires a targeting key for each evaluation.

I edited the title and the description accordingly, to reflect only negative flow which is less severe.

Included solution at the [PR](https://github.com/open-feature/java-sdk-contrib/pull/403).

**Comment by thomaspoignant** [comment]
@liran2000 could we close this issue.
We were throwing [InvalidTargetingKey](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/go-feature-flag/src/main/java/dev/openfeature/contrib/providers/gofeatureflag/bean/GoFeatureFlagUser.java#L32) because the other exception was not existing before.

**Comment by liran2000** [comment]
Yes, resolved by #403.
