### ISSUE TITLE
[flagd] implement `flagd.feature` gherkin test suite

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#459]
We don't yet have e2e tests for flag changes or zero-value flags.

These are both defined in the [flagd.feature](https://github.com/open-feature/flagd-testbed/blob/main/gherkin/flagd.feature) test suite, and supported by the `sync-testbed` and `flagd-testbed` containers.

Tasks:

- [x] add matching steps defined in the feature file to the [steps](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/steps/StepDefinitions.java)
  - note the `Flag change event` should fire automatically from both testbed containers, so there's no need to _manually_ change the flags
- [x] load the feature file in both cucumber runs ([RPC](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/RunFlagdRpcCucumberTest.java) and [in-process](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/RunFlagdInProcessCucumberTest.java))

**Comment by DBlanchard88** [comment]
Hello, I am interested in doing this one

**Comment by toddbaert** [comment]
Thanks @DBlanchard88 . Assigned.

Let me know if you need any help.

**Comment by toddbaert** [comment]
Completed with https://github.com/open-feature/java-sdk-contrib/pull/468
