### ISSUE TITLE
[flagd/in-process] float flags with 0.0 value are parsed as ints

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#470]
The flagd in-process provider _should_ be able to resolve ints as floats, and vice-versa.

To fix:

- modify [this](https://github.com/open-feature/java-sdk-contrib/blob/3190ad2bbc4746eb7efb571af14c73cba7176ea0/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java#L190) area of the code to support conversion from int/float, float/int
- add relevant tests [here](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolverTest.java)
- un-comment float tests [here](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/steps/StepDefinitions.java)

Background:

_Originally posted by @toddbaert in https://github.com/open-feature/java-sdk-contrib/pull/468#discussion_r1342179921_

**Comment by Kavindu-Dodan** [comment]
I summarised my findings here - https://github.com/open-feature/java-sdk-contrib/pull/468/files#r1344520202 

IMO this can be safely fixed at the in-process provider end. A special handling for Double should fix this

**Comment by toddbaert** [comment]
> IMO this can be safely fixed at the in-process provider end. A special handling for Double should fix this

I was thinking this too... in fact, to be consistent with RPC, I think we have to attempt conversion in both directions, int -> float and float -> int (RPC does this). Additionally, if we do this, we may need to specify how the float -> int conversion is done... I think Java and Go both round toward zero... I believe .NET does too. This might be worth specifying.

I will proceed with a fix as described above unless @Kavindu-Dodan or @beeme1mr disagrees.

**Comment by beeme1mr** [comment]
Yes, I agree that we should cast the values. This should be documented in the spec.

**Comment by DBlanchard88** [comment]
I think i understand how to do this. Ill take a shot at it.

**Comment by toddbaert** [comment]
> I think i understand how to do this. Ill take a shot at it.

Alright, cool. Assigned.
