### ISSUE TITLE
[flagd] Add `$flagd.timestamp` to in-process evalutor

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#490]
The flagd in-process evaluator needs to have `$flagd.timestamp` added, so that users can write time-based JsonLogic rules.

See [here](https://flagd.dev/reference/flag-definitions/?h=timestamp#flagd-properties-in-the-evaluation-context) for doc, and [here](https://github.com/open-feature/flagd/blob/3dd69297c4dcf87f4780432600903fd3f76916fb/core/pkg/eval/json_evaluator.go#L325-L328) for the flagd-standalone implementation.

You'll need to add a standard unix timestamp (seconds since 1970) to the evaluation context, similar to the flagKey, [here](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/targeting/Operator.java#L38).

**Comment by DBlanchard88** [comment]
ill do it

**Comment by toddbaert** [comment]
Relates to: https://github.com/open-feature/flagd-testbed/issues/74

**Comment by toddbaert** [comment]
Done with https://github.com/open-feature/java-sdk-contrib/pull/512

Thanks @DBlanchard88 !
