### ISSUE TITLE
Activate Checkstyle rule to avoid star imports

### ISSUE THREAD

**Issue by aepfli** [open-feature/java-sdk-contrib#816]
The usage of Star imports within java is generally seen as a bad practice as it leads to tight coupling between packages and might lead to problems when a new version of a library introduces name clashes. see https://checkstyle.sourceforge.io/version/4.4/5.x/config_imports.html - as we do have a tool in place which can prevent the usage, we should activate the rule 

```
<module name="AvoidStarImport">
</module>
```

see the already raised nit in a pull request https://github.com/open-feature/java-sdk-contrib/pull/810#discussion_r1631573948

wdyt?

**Comment by aepfli** [comment]
thank you for merging this, with a great surprise i realised that checkstyle is not run for test sources do you think this would be desirable? i can proide a pr, but there are a lot of tests which are violating basic naming and formatting conventions, so this would take some time. on the other hand it would be a good first issue.

**Comment by Kavindu-Dodan** [comment]
> thank you for merging this, with a great surprise i realised that checkstyle is not run for test sources do you think this would be desirable? i can proide a pr, but there are a lot of tests which are violating basic naming and formatting conventions, so this would take some time. on the other hand it would be a good first issue.

hmm that's strange. We only exclude generated sources through suppression xml [1] . Do you have a clue on why tests are ignores ? 

[1] - https://github.com/open-feature/java-sdk-contrib/blob/main/checkstyle-suppressions.xml

**Comment by aepfli** [comment]
```
        <includeTestSourceDirectory>true</includeTestSourceDirectory>
```

is missing in the checkstyle config
