### ISSUE TITLE
[feat] add JUnit Pioneer to dev dependencies

### ISSUE THREAD

**Issue by aepfli** [open-feature/java-sdk-contrib#818]
While developing https://github.com/open-feature/java-sdk-contrib/pull/810, we saw the need for overwriting environment variables during testing. As this is not a trivial task to do, we looked for easy-to-use alternatives in the JUnit world and 'stumbled' upon [JUnit Pioneer.](https://junit-pioneer.org/docs/)

JUnit Pioneer offers a great set of additional utilities for JUnit tests, like setting env variables, setting system properties, default locales, etc. This could be a great extension of our testing capabilities without adding another dependency for our provided libraries.o

wdyt?

**Comment by Kavindu-Dodan** [comment]
+1 from my end as this enables provider authors to test the behavior based on environment variables.
