### ISSUE TITLE
Add OTel Hook Implementation

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#93]
Add OTel hook implementation plus tests.

See https://github.com/open-feature/node-sdk-contrib/tree/main/libs/hooks/open-telemetry

**Comment by ceekay47** [comment]
Hi @toddbaert, I would like to work on this. Can you please assign me this issue?

**Comment by toddbaert** [comment]
Assigned. Please take a look at the link the node repo. We already have a stub package being publish for this. You just need to add the functionality here: https://github.com/open-feature/java-sdk-contrib/blob/main/hooks/open-telemetry/src/main/java/dev/openfeature/contrib/hooks/otel/OpenTelemetryHook.java

Please make sure to add unit tests.

You can you [zipkin](https://zipkin.io/) to make sure the telemetry is being added properly if you like.

**Comment by ceekay47** [comment]
Thanks! I will work on this and let you know if I have any questions.

**Comment by beeme1mr** [comment]
Closing in favor of [this issue](https://github.com/open-feature/java-sdk-contrib/issues/144). We can build a plugin to spec now that the OTel team has officially approved and merged the proposal.

@ceekay47, is this something you're interested in working on still? Please comment in the other issue if you are and I'll assign the issue to you.
