### ISSUE TITLE
Rename FLAGD_KEEP_ALIVE_TIME to FLAGD_KEEP_ALIVE_TIME_MS

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#935]
This env_var name is unclear, and inconsistent with the DEADLINE. We should rename it to FLAGD_KEEP_ALIVE_TIME_MS but also still support the old env var.

See: https://github.com/open-feature/java-sdk-contrib/blob/c598d9f0a61f2324fb85d72fdfea34811283c575/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/Config.java#L36

**Comment by alexandraoberaigner** [comment]
Hi @toddbaert, I'd like to take this
