### ISSUE TITLE
Add env var & socket support for flagd provider

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#95]
- Add env var reading for configuration (see: https://github.com/open-feature/golang-sdk-contrib/blob/eabb362ad36cf032ff277ecfd91e584d096b00dd/providers/flagd/pkg/provider.go#L92)
- Add unix socket support
- Do NOT add HTTP support (GRPC only)

**Comment by beeme1mr** [comment]
https://github.com/open-feature/java-sdk-contrib/tree/main/providers/flagd
