### ISSUE TITLE
Flipt Provider does not return Structure values for Structure evaluations

### ISSUE THREAD

**Issue by alexcardell** [open-feature/java-sdk-contrib#955]
# Problem 

[Line](https://github.com/open-feature/java-sdk-contrib/blob/03dfc91ae5bb47de90129abefc1146daa496ea17/providers/flipt/src/main/java/dev/openfeature/contrib/providers/flipt/FliptProvider.java#L214)

Flipt Provider only assigns the variant attachment (the JSON structure attached to the flag) as metadata, not a value. It uses the variant key (variant name) as the value, always returning a string key, which is a valid Value

**Comment by beeme1mr** [comment]
Hey @markphelps, could you please take a look at this?

**Comment by markphelps** [comment]
@alexcardell I think this is indeed a bug as in the JavaScript impl we do the following:

```javascript
      const flagValue: PrimitiveType | U = validateFlagType(
        flagType,
        flagType === 'json' ? variantEvaluation.variantAttachment : variantEvaluation.variantKey,
      );
```

https://github.com/open-feature/js-sdk-contrib/blob/29c3669676fb4526feba1d51fd344a71247c4c3f/libs/providers/flipt/src/lib/flipt-provider.ts#L179-L183

So if the user requests a JSON/Object flag type we should return the JSON value (the attachment) as you pointed out.

We should probably go through our other OpenFeature providers as well to ensure consistent behavior.

I can create a fix for this one, or if you are able to that would be great as well.
