### ISSUE TITLE
[flagd] Support custom schemes (name resolvers)

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk-contrib#995]
As described [here](https://github.com/open-feature/flagd/blob/main/docs/reference/specifications/proposal/rfc-grpc-custom-name-resolver.md), we wish to support [custom name revolvers](https://grpc.io/docs/guides/custom-name-resolution/) for additional control and configuration according to user's infrastructure. In order to make use of this, we must support the creation of channels created with [NettyChannelBuilder.forTarget](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyChannelBuilder.html#forTarget(java.lang.String)), and expose an option in the flagd that use a "target string" instead of a host/port combination.

Requirements:

- optional usage of channel built using `.forTarget` (see: https://github.com/open-feature/java-sdk-contrib/blob/4197d3231d68fb686b61ac1ca5eb8c278044a0e3/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/common/ChannelBuilder.java#L30)
- changes in options to allow specifying a target string
  - support env-var based configuration as well, as with existing options
  - consistent with https://github.com/open-feature/go-sdk-contrib/issues/585
- no breaking changes
- associated unit tests (e2e not necessary)

cc @pradeepbbl

**Comment by pradeepbbl** [comment]
sounds good to me and I'm happy to work on it

**Comment by toddbaert** [comment]
> sounds good to me and I'm happy to work on it

assigned!
